CREATE TABLE IF NOT EXISTS BalanceSheet (
    symbol VARCHAR(10) NOT NULL,
    fiscalDateEnding DATE NOT NULL,
    reportedCurrency VARCHAR(3) NOT NULL,
    totalAssets BIGINT,
    totalCurrentAssets BIGINT,
    cashAndCashEquivalentsAtCarryingValue BIGINT,
    cashAndShortTermInvestments BIGINT,
    inventory BIGINT,
    currentNetReceivables BIGINT,
    totalNonCurrentAssets BIGINT,
    propertyPlantEquipment BIGINT,
    accumulatedDepreciationAmortizationPPE BIGINT,
    intangibleAssets BIGINT,
    intangibleAssetsExcludingGoodwill BIGINT,
    goodwill BIGINT,
    investments BIGINT,
    longTermInvestments BIGINT,
    shortTermInvestments BIGINT,
    otherCurrentAssets BIGINT,
    otherNonCurrentAssets BIGINT,
    totalLiabilities BIGINT,
    totalCurrentLiabilities BIGINT,
    currentAccountsPayable BIGINT,
    deferredRevenue BIGINT,
    currentDebt BIGINT,
    shortTermDebt BIGINT,
    totalNonCurrentLiabilities BIGINT,
    capitalLeaseObligations BIGINT,
    longTermDebt BIGINT,
    currentLongTermDebt BIGINT,
    longTermDebtNoncurrent BIGINT,
    shortLongTermDebtTotal BIGINT,
    otherCurrentLiabilities BIGINT,
    otherNonCurrentLiabilities BIGINT,
    totalShareholderEquity BIGINT,
    treasuryStock BIGINT,
    retainedEarnings BIGINT,
    commonStock BIGINT,
    commonStockSharesOutstanding BIGINT,
    PRIMARY KEY (symbol, fiscalDateEnding, reportedCurrency)
);

CREATE INDEX IF NOT EXISTS bsheetidx ON BalanceSheet(symbol, fiscalDateEnding);
