CREATE TABLE IF NOT EXISTS CompanyOverview (
    symbol VARCHAR(10) NOT NULL,
    assetType VARCHAR(255),
    name TEXT NOT NULL,
    description TEXT,
    cik VARCHAR(255),
    exchange VARCHAR(255),
    currency VARCHAR(20),
    country VARCHAR(255),
    sector VARCHAR(255),
    industry VARCHAR(255),
    address TEXT,
    fiscalYearEnd VARCHAR(255),
    latestQuarter DATE,
    marketCapitalization BIGINT,
    ebitda BIGINT,
    peRatio DECIMAL(10, 2),
    pegRatio DECIMAL(10, 3),
    bookValue DECIMAL(10, 2),
    dividendPerShare DECIMAL(10, 2),
    dividendYield DECIMAL(10, 4),
    eps DECIMAL(10, 2),
    revenuePerShareTTM DECIMAL(10, 2),
    profitMargin DECIMAL(10, 4),
    operatingMarginTTM DECIMAL(10, 3),
    returnOnAssetsTTM DECIMAL(10, 4),
    returnOnEquityTTM DECIMAL(10, 3),
    revenueTTM BIGINT,
    grossProfitTTM BIGINT,
    dilutedEPSTTM DECIMAL(10, 2),
    quarterlyEarningsGrowthYOY DECIMAL(10, 3),
    quarterlyRevenueGrowthYOY DECIMAL(10, 3),
    analystTargetPrice DECIMAL(10, 2),
    trailingPE DECIMAL(10, 2),
    forwardPE DECIMAL(10, 2),
    priceToSalesRatioTTM DECIMAL(10, 3),
    priceToBookRatio DECIMAL(10, 2),
    evToRevenue DECIMAL(10, 3),
    evToEBITDA DECIMAL(10, 2),
    beta DECIMAL(10, 3),
    _52WeekHigh DECIMAL(10, 2),
    _52WeekLow DECIMAL(10, 2),
    _50DayMovingAverage DECIMAL(10, 2),
    _200DayMovingAverage DECIMAL(10, 2),
    sharesOutstanding BIGINT,
    dividendDate DATE,
    exDividendDate DATE,
    PRIMARY KEY (symbol)
);

CREATE INDEX IF NOT EXISTS companyidx ON CompanyOverview(symbol);
